### ISSUE TITLE
割り算、小数点以下四捨五入ができていないかも?

### ISSUE THREAD

**Issue by monokemonoke** [monokemonoke/git-practice-20220610#4]
## 操作手順
* `3 ÷ 2`,  `小数点以下四捨五入` で計算したら
* `1` になった

## 本来の想定
* `3 ÷ 2`,  `小数点以下四捨五入` で計算したら
* `2` になってほしい...(はず)

## 操作環境
* OS macOS Monterey
* OSバージョン 12.04
* ブラウザ Brave
* ブラウザバージョン バージョン: 1.39.120 Chromium: 102.0.5005.99（Official Build） （x86_64）

**Comment by hinoki122** [comment]
よかったよ
